# Projects Fields
# This file contains the field names used in the Fredon project data structure.
PROJECT_NAME = 2
PROJECT_ID = 1
LOCATION = None
POST_CODE = None
CLIENT_SECTOR = 7
PORTFOLIO_BUS_UNIT_DEPT_ID = 3
ASSET_TYPE = None
CONTRACT_TYPE = None
CONTRACT_FINANCIAL = 6
CLIENT = 4
STAGE_OF_WORK = 5

# Financial Fields
DATE= 9
APPROVED_BUDGET = 14
FORECAST_END_DATE = None
FORECAST_FINAL_COST = 34
CONTINGENCY_REMAINING =None 
ACTUAL_COST_TO_DATE =26
FORECAST_FINAL_REVENUE =15
ACTUAL_REVENUE_TO_DATE =36 
