# Projects Fields
# This file contains the field names used in the Fredon project data structure.
PROJECT_ID = 1
PROJECT_NAME = 2

LOCATION = 4
POST_CODE = None
CLIENT_SECTOR = 8
PORTFOLIO_BUS_UNIT_DEPT_ID = 3
ASSET_TYPE = None
CONTRACT_TYPE = 9
CONTRACT_FINANCIAL = 7
CLIENT = 5
STAGE_OF_WORK = 6
PERCENTAGE_COMPLETE = 42
# Financial Fields
DATE= 10
APPROVED_BUDGET = 15
FORECAST_END_DATE = 22
FORECAST_FINAL_COST = 23
CONTINGENCY_REMAINING =24
ACTUAL_COST_TO_DATE =25
FORECAST_FINAL_REVENUE =26
ACTUAL_REVENUE_TO_DATE =39 
COMMENTS = 5
NOTES = 42
