# Projects Fields
# This file contains the field names used in the Fredon project data structure.
# PROJECT_ID = 1
# PROJECT_NAME = 2

# LOCATION = 4
# POST_CODE = None
# CLIENT_SECTOR = 8
# PORTFOLIO_BUS_UNIT_DEPT_ID = 3
# ASSET_TYPE = None
# CONTRACT_TYPE = 9
# CONTRACT_FINANCIAL = 7
# CLIENT = 5
# STAGE_OF_WORK = 6
# PERCENTAGE_COMPLETE = 42
# # Financial Fields
# DATE= 10
# APPROVED_BUDGET = 15
# FORECAST_END_DATE = 22
# FORECAST_FINAL_COST = 23
# CONTINGENCY_REMAINING =24
# ACTUAL_COST_TO_DATE =25
# FORECAST_FINAL_REVENUE =26
# ACTUAL_REVENUE_TO_DATE =39 
# COMMENTS = 5
# NOTES = 42

#Symal fields 
PROJECT_ID = 0 ###DONE###
PROJECT_NAME = 151 ###DONE###

LOCATION = 153 ###DONE###
POST_CODE = 156 ###DONE###
CLIENT_SECTOR = None ###DONE###
PORTFOLIO_BUS_UNIT_DEPT_ID = 189 ###DONE###
ASSET_TYPE = None ###DONE###
CONTRACT_TYPE = 161 ###DONE###
CONTRACT_FINANCIAL = None ###DONE###
CLIENT = 173 ###DONE###
STAGE_OF_WORK = None
PERCENTAGE_COMPLETE = 124 ###DONE###
# Financial Fields
DATE= 1 ###DONE###
APPROVED_BUDGET = 31 ###DONE###
FORECAST_END_DATE = 158 ### Used Original PC Date###
FORECAST_FINAL_COST = 3 ###DONE###
CONTINGENCY_REMAINING = None ###DONE###
ACTUAL_COST_TO_DATE =5 ###DONE###
FORECAST_FINAL_REVENUE =2 ###DONE###
ACTUAL_REVENUE_TO_DATE =7 ###DONE###
COMMENTS = None ###DONE###
NOTES = 124 ###DONE###
